Fix CI error
src/hatch/env/collectors/plugin/hooks.py:15: error: Unused "type: ignore"
comment  [unused-ignore]
        return [CustomEnvironmentCollector, DefaultEnvironmentCollector]  ...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...
backend/src/hatchling/builders/hooks/plugin/hooks.py:15: error: Unused
"type: ignore" comment  [unused-ignore]
        return [CustomBuildHook, VersionBuildHook]  # type: ignore[list-it...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~